POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Amit",
  "email": "amit2@test.com",
  "password": "password123"
}

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Priya",
  "email": "priya@test.com",
  "password": "password123"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "amit@test.com",
  "password": "password123"
}

###

POST http://localhost:5000/api/expenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhODBhYjlmOGMyMWEyZjRjNTIxZGM4ZSIsImlhdCI6MTc4Njg4ODEzNywiZXhwIjoxNzg3NDkyOTM3fQ.E3cDupR80ucUS7qGIfnKR8p78zlTNk1YSF2fv7W_Nqc

{
  "description": "Beach shack lunch",
  "amount": 40,
  "paidBy": "Amit",
  "splitBetween": ["Amit"],
  "groupId": "6a80be3dbefe5b7db2a4fec1"
}

###

GET http://localhost:5000/api/expenses/6a80be3dbefe5b7db2a4fec1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhODBhYjlmOGMyMWEyZjRjNTIxZGM4ZSIsImlhdCI6MTc4Njg4ODEzNywiZXhwIjoxNzg3NDkyOTM3fQ.E3cDupR80ucUS7qGIfnKR8p78zlTNk1YSF2fv7W_Nqc

###

POST http://localhost:5000/api/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhODBhYjlmOGMyMWEyZjRjNTIxZGM4ZSIsImlhdCI6MTc4Njg4ODEzNywiZXhwIjoxNzg3NDkyOTM3fQ.E3cDupR80ucUS7qGIfnKR8p78zlTNk1YSF2fv7W_Nqc

{
  "name": "Trip with Priya",
  "memberIds": ["6a81c8a22c1daaa06e51dff8"]
}

###

POST http://localhost:5000/api/expenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhODBhYjlmOGMyMWEyZjRjNTIxZGM4ZSIsImlhdCI6MTc4Njg4ODEzNywiZXhwIjoxNzg3NDkyOTM3fQ.E3cDupR80ucUS7qGIfnKR8p78zlTNk1YSF2fv7W_Nqc

{
  "description": "Beach shack lunch",
  "amount": 40,
  "paidBy": "6a80ab9f8c21a2f4c521dc8e",
  "splitBetween": ["6a80ab9f8c21a2f4c521dc8e", "6a81c8a22c1daaa06e51dff8"],
  "groupId": "6a81f29084f55fca1ba4d3e5"
}

###

GET http://localhost:5000/api/groups/6a81f29084f55fca1ba4d3e5/balances
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhODBhYjlmOGMyMWEyZjRjNTIxZGM4ZSIsImlhdCI6MTc4Njg4ODEzNywiZXhwIjoxNzg3NDkyOTM3fQ.E3cDupR80ucUS7qGIfnKR8p78zlTNk1YSF2fv7W_Nqc

###

GET http://localhost:5000/api/groups/6a81f29084f55fca1ba4d3e5/settle-up
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhODBhYjlmOGMyMWEyZjRjNTIxZGM4ZSIsImlhdCI6MTc4Njg4ODEzNywiZXhwIjoxNzg3NDkyOTM3fQ.E3cDupR80ucUS7qGIfnKR8p78zlTNk1YSF2fv7W_Nqc